
# ========= Border =========
file_panel_border = '#C9A7C3'
sidebar_border = '#C9A7C3'
footer_border = '#C9A7C3'

# ========= Border Active =========
file_panel_border_active = '#9c9dba'
sidebar_border_active = '#9c9dba'
footer_border_active = '#9c9dba'
modal_border_active = '#9c9dba'

# ========= Background (bg) =========
full_screen_bg = '#022A38'
file_panel_bg = '#022A38'
sidebar_bg = '#022A38'
footer_bg = '#022A38'
modal_bg = '#022A38'

# ========= Foreground (fg) =========
full_screen_fg = '#eddfea'
file_panel_fg = '#eddfea'
sidebar_fg = '#eddfea'
footer_fg = '#eddfea'
modal_fg = '#eddfea'

# ========= Special Color =========
cursor = '#eddfea'
correct = '#68cfa3'
error = '#CD5BA3'
hint = '#86e7ee'
cancel = '#CD5BA3'
gradient_color = ['#022A38', "#5ca9c4"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#022A38'
file_panel_top_path = '#5ca9c4'
file_panel_item_selected_fg = '#5ca9c4'
file_panel_item_selected_bg = '#022A38'

# ========= Sidebar Special Items =========
sidebar_title = '#eddfea'
sidebar_item_selected_fg = '#5ca9c4'
sidebar_item_selected_bg = '#022A38'
sidebar_divider = '#C9A7C3'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#CD5BA3'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#68cfa3'
